grafana:
  ingress:
    enabled: true

    ingressClassName: nginx-backend

    annotations:
      cert-manager.io/cluster-issuer: prod-issuer

    hosts:
      - grafana-br-tr.targeted.work

    path: /

    tls:
      - secretName: grafana-tls
        hosts:
          - grafana-br-tr.targeted.work

prometheus:
  ingress:
    enabled: true

    ingressClassName: nginx-backend

    annotations:
      cert-manager.io/cluster-issuer: prod-issuer

      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Prometheus Login"

    hosts:
      - prometheus-br-tr.targeted.work

    paths:
      - /

    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus-br-tr.targeted.work

alertmanager:
  ingress:
    enabled: true

    ingressClassName: nginx-backend

    annotations:
      cert-manager.io/cluster-issuer: prod-issuer

      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: alertmanager-basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Alertmanager Login"

    hosts:
      - alertmanager-br-tr.targeted.work

    paths:
      - /

    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager-br-tr.targeted.work
